name: Build Sofle RGB

on:
  push:
    branches:
      - main
    paths:
      - "app/boards/shields/sofle/**"
      - "app/dts/layouts/josefadamcik/**"
      - "app/boards/nicekeyboards/**"
      - "app/west.yml"
      - ".github/workflows/build-sofle.yml"
  pull_request:
    paths:
      - "app/boards/shields/sofle/**"
      - "app/dts/layouts/josefadamcik/**"
      - "app/boards/nicekeyboards/**"
      - "app/west.yml"
      - ".github/workflows/build-sofle.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/zmkfirmware/zmk-build-arm:4.1
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano
            shield: sofle_left
          - board: nice_nano
            shield: sofle_right
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Cache west modules
        uses: actions/cache@v5
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('app/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
        timeout-minutes: 2
        continue-on-error: true

      - name: Initialize workspace (west init)
        run: west init -l app

      - name: Update modules (west update)
        run: west update --fetch-opt=--filter=tree:0

      - name: Export Zephyr CMake package (west zephyr-export)
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s app -p -b ${{ matrix.board }} -- -DSHIELD="${{ matrix.shield }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}-${{ matrix.board }}
          path: build/zephyr/zmk.uf2
